'use strict';

const ERROR_FIELD_ID_MAP = {
  severity: 'S',
  code: 'C',
  message: 'M',
  detail: 'D',
  hint: 'H',
  position: 'P',
  internal_position: 'p',
  internal_query: 'q',
  where: 'W',
  schema: 's',
  table: 't',
  column: 'c',
  data_type: 'd',
  contraint: 'n',
  file: 'F',
  line: 'L',
  routine: 'R',
};

const SQLSTATE_ERROR_CODE_MAP = {
  // Class 00 — Successful Completion
  successful_completion: "00000",
  // Class 01 — Warning
  warning: "01000",
  dynamic_result_sets_returned: "0100C",
  implicit_zero_bit_padding: "01008",
  null_value_eliminated_in_set_function: "01003",
  privilege_not_granted: "01007",
  privilege_not_revoked: "01006",
  string_data_right_truncation: "01004",
  deprecated_feature: "01P01",
  // Class 02 — No Data (this is also a warning class per the SQL standard)
  no_data: "02000",
  no_additional_dynamic_result_sets_returned: "02001",
  // Class 03 — SQL Statement Not Yet Complete
  sql_statement_not_yet_complete: "03000",
  // Class 08 — Connection Exception
  connection_exception: "08000",
  connection_does_not_exist: "08003",
  connection_failure: "08006",
  sqlclient_unable_to_establish_sqlconnection: "08001",
  sqlserver_rejected_establishment_of_sqlconnection: "08004",
  transaction_resolution_unknown: "08007",
  protocol_violation: "08P01",
  // Class 09 — Triggered Action Exception
  triggered_action_exception: "09000",
  // Class 0A — Feature Not Supported
  feature_not_supported: "0A000",
  // Class 0B — Invalid Transaction Initiation
  invalid_transaction_initiation: "0B000",
  // Class 0F — Locator Exception
  locator_exception: "0F000",
  invalid_locator_specification: "0F001",
  // Class 0L — Invalid Grantor
  invalid_grantor: "0L000",
  invalid_grant_operation: "0LP01",
  // Class 0P — Invalid Role Specification
  invalid_role_specification: "0P000",
  // Class 0Z — Diagnostics Exception
  diagnostics_exception: "0Z000",
  stacked_diagnostics_accessed_without_active_handler: "0Z002",
  // Class 20 — Case Not Found
  case_not_found: "20000",
  // Class 21 — Cardinality Violation
  cardinality_violation: "21000",
  // Class 22 — Data Exception
  data_exception: "22000",
  array_subscript_error: "2202E",
  character_not_in_repertoire: "22021",
  datetime_field_overflow: "22008",
  division_by_zero: "22012",
  error_in_assignment: "22005",
  escape_character_conflict: "2200B",
  indicator_overflow: "22022",
  interval_field_overflow: "22015",
  invalid_argument_for_logarithm: "2201E",
  invalid_argument_for_ntile_function: "22014",
  invalid_argument_for_nth_value_function: "22016",
  invalid_argument_for_power_function: "2201F",
  invalid_argument_for_width_bucket_function: "2201G",
  invalid_character_value_for_cast: "22018",
  invalid_datetime_format: "22007",
  invalid_escape_character: "22019",
  invalid_escape_octet: "2200D",
  invalid_escape_sequence: "22025",
  nonstandard_use_of_escape_character: "22P06",
  invalid_indicator_parameter_value: "22010",
  invalid_parameter_value: "22023",
  invalid_regular_expression: "2201B",
  invalid_row_count_in_limit_clause: "2201W",
  invalid_row_count_in_result_offset_clause: "2201X",
  invalid_time_zone_displacement_value: "22009",
  invalid_use_of_escape_character: "2200C",
  most_specific_type_mismatch: "2200G",
  null_value_not_allowed: "22004",
  null_value_no_indicator_parameter: "22002",
  numeric_value_out_of_range: "22003",
  string_data_length_mismatch: "22026",
  string_data_right_truncation: "22001",
  substring_error: "22011",
  trim_error: "22027",
  unterminated_c_string: "22024",
  zero_length_character_string: "2200F",
  floating_point_exception: "22P01",
  invalid_text_representation: "22P02",
  invalid_binary_representation: "22P03",
  bad_copy_file_format: "22P04",
  untranslatable_character: "22P05",
  not_an_xml_document: "2200L",
  invalid_xml_document: "2200M",
  invalid_xml_content: "2200N",
  invalid_xml_comment: "2200S",
  invalid_xml_processing_instruction: "2200T",
  // Class 23 — Integrity Constraint Violation
  integrity_constraint_violation: "23000",
  restrict_violation: "23001",
  not_null_violation: "23502",
  foreign_key_violation: "23503",
  unique_violation: "23505",
  check_violation: "23514",
  exclusion_violation: "23P01",
  // Class 24 — Invalid Cursor State
  invalid_cursor_state: "24000",
  // Class 25 — Invalid Transaction State
  invalid_transaction_state: "25000",
  active_sql_transaction: "25001",
  branch_transaction_already_active: "25002",
  held_cursor_requires_same_isolation_level: "25008",
  inappropriate_access_mode_for_branch_transaction: "25003",
  inappropriate_isolation_level_for_branch_transaction: "25004",
  no_active_sql_transaction_for_branch_transaction: "25005",
  read_only_sql_transaction: "25006",
  schema_and_data_statement_mixing_not_supported: "25007",
  no_active_sql_transaction: "25P01",
  in_failed_sql_transaction: "25P02",
  // Class 26 — Invalid SQL Statement Name
  invalid_sql_statement_name: "26000",
  // Class 27 — Triggered Data Change Violation
  triggered_data_change_violation: "27000",
  // Class 28 — Invalid Authorization Specification
  invalid_authorization_specification: "28000",
  invalid_password: "28P01",
  // Class 2B — Dependent Privilege Descriptors Still Exist
  dependent_privilege_descriptors_still_exist: "2B000",
  dependent_objects_still_exist: "2BP01",
  // Class 2D — Invalid Transaction Termination
  invalid_transaction_termination: "2D000",
  // Class 2F — SQL Routine Exception
  sql_routine_exception: "2F000",
  function_executed_no_return_statement: "2F005",
  modifying_sql_data_not_permitted: "2F002",
  prohibited_sql_statement_attempted: "2F003",
  reading_sql_data_not_permitted: "2F004",
  // Class 34 — Invalid Cursor Name
  invalid_cursor_name: "34000",
  // Class 38 — External Routine Exception
  external_routine_exception: "38000",
  containing_sql_not_permitted: "38001",
  modifying_sql_data_not_permitted: "38002",
  prohibited_sql_statement_attempted: "38003",
  reading_sql_data_not_permitted: "38004",
  // Class 39 — External Routine Invocation Exception
  external_routine_invocation_exception: "39000",
  invalid_sqlstate_returned: "39001",
  null_value_not_allowed: "39004",
  trigger_protocol_violated: "39P01",
  srf_protocol_violated: "39P02",
  // Class 3B — Savepoint Exception
  savepoint_exception: "3B000",
  invalid_savepoint_specification: "3B001",
  // Class 3D — Invalid Catalog Name
  invalid_catalog_name: "3D000",
  // Class 3F — Invalid Schema Name
  invalid_schema_name: "3F000",
  // Class 40 — Transaction Rollback
  transaction_rollback: "40000",
  transaction_integrity_constraint_violation: "40002",
  serialization_failure: "40001",
  statement_completion_unknown: "40003",
  deadlock_detected: "40P01",
  // Class 42 — Syntax Error or Access Rule Violation
  syntax_error_or_access_rule_violation: "42000",
  syntax_error: "42601",
  insufficient_privilege: "42501",
  cannot_coerce: "42846",
  grouping_error: "42803",
  windowing_error: "42P20",
  invalid_recursion: "42P19",
  invalid_foreign_key: "42830",
  invalid_name: "42602",
  name_too_long: "42622",
  reserved_name: "42939",
  datatype_mismatch: "42804",
  indeterminate_datatype: "42P18",
  collation_mismatch: "42P21",
  indeterminate_collation: "42P22",
  wrong_object_type: "42809",
  undefined_column: "42703",
  undefined_function: "42883",
  undefined_table: "42P01",
  undefined_parameter: "42P02",
  undefined_object: "42704",
  duplicate_column: "42701",
  duplicate_cursor: "42P03",
  duplicate_database: "42P04",
  duplicate_function: "42723",
  duplicate_prepared_statement: "42P05",
  duplicate_schema: "42P06",
  duplicate_table: "42P07",
  duplicate_alias: "42712",
  duplicate_object: "42710",
  ambiguous_column: "42702",
  ambiguous_function: "42725",
  ambiguous_parameter: "42P08",
  ambiguous_alias: "42P09",
  invalid_column_reference: "42P10",
  invalid_column_definition: "42611",
  invalid_cursor_definition: "42P11",
  invalid_database_definition: "42P12",
  invalid_function_definition: "42P13",
  invalid_prepared_statement_definition: "42P14",
  invalid_schema_definition: "42P15",
  invalid_table_definition: "42P16",
  invalid_object_definition: "42P17",
  // Class 44 — WITH CHECK OPTION Violation
  with_check_option_violation: "44000",
  // Class 53 — Insufficient Resources
  insufficient_resources: "53000",
  disk_full: "53100",
  out_of_memory: "53200",
  too_many_connections: "53300",
  configuration_limit_exceeded: "53400",
  // Class 54 — Program Limit Exceeded
  program_limit_exceeded: "54000",
  statement_too_complex: "54001",
  too_many_columns: "54011",
  too_many_arguments: "54023",
  // Class 55 — Object Not In Prerequisite State
  object_not_in_prerequisite_state: "55000",
  object_in_use: "55006",
  cant_change_runtime_param: "55P02",
  lock_not_available: "55P03",
  // Class 57 — Operator Intervention
  operator_intervention: "57000",
  query_canceled: "57014",
  admin_shutdown: "57P01",
  crash_shutdown: "57P02",
  cannot_connect_now: "57P03",
  database_dropped: "57P04",
  // Class 58 — System Error (errors external to PostgreSQL itself)
  system_error: "58000",
  io_error: "58030",
  undefined_file: "58P01",
  duplicate_file: "58P02",
  // Class F0 — Configuration File Error
  config_file_error: "F0000",
  lock_file_exists: "F0001",
  // Class HV — Foreign Data Wrapper Error (SQL/MED)
  fdw_error: "HV000",
  fdw_column_name_not_found: "HV005",
  fdw_dynamic_parameter_value_needed: "HV002",
  fdw_function_sequence_error: "HV010",
  fdw_inconsistent_descriptor_information: "HV021",
  fdw_invalid_attribute_value: "HV024",
  fdw_invalid_column_name: "HV007",
  fdw_invalid_column_number: "HV008",
  fdw_invalid_data_type: "HV004",
  fdw_invalid_data_type_descriptors: "HV006",
  fdw_invalid_descriptor_field_identifier: "HV091",
  fdw_invalid_handle: "HV00B",
  fdw_invalid_option_index: "HV00C",
  fdw_invalid_option_name: "HV00D",
  fdw_invalid_string_length_or_buffer_size: "HV090",
  fdw_invalid_string_format: "HV00A",
  fdw_invalid_use_of_null_pointer: "HV009",
  fdw_too_many_handles: "HV014",
  fdw_out_of_memory: "HV001",
  fdw_no_schemas: "HV00P",
  fdw_option_name_not_found: "HV00J",
  fdw_reply_handle: "HV00K",
  fdw_schema_not_found: "HV00Q",
  fdw_table_not_found: "HV00R",
  fdw_unable_to_create_execution: "HV00L",
  fdw_unable_to_create_reply: "HV00M",
  fdw_unable_to_establish_connection: "HV00N",
  // Class P0 — PL/pgSQL Error
  plpgsql_error: "P0000",
  raise_exception: "P0001",
  no_data_found: "P0002",
  too_many_rows: "P0003",
  // Class XX — Internal Error
  internal_error: "XX000",
  data_corrupted: "XX001",
  index_corrupted: "XX002",
};

const PG_TYPE_MAP = {
  bool: {
    oid: 16,
    name: "bool",
    size: 1,
    is_array: false,
  },
  bytea: {
    oid: 17,
    name: "bytea",
    size: -1,
    is_array: false,
  },
  char: {
    oid: 18,
    name: "char",
    size: 1,
    is_array: false,
  },
  name: {
    oid: 19,
    name: "name",
    size: 64,
    is_array: true,
    element_type: "char",
  },
  int8: {
    oid: 20,
    name: "int8",
    size: 8,
    is_array: false,
  },
  int2: {
    oid: 21,
    name: "int2",
    size: 2,
    is_array: false,
  },
  int2vector: {
    oid: 22,
    name: "int2vector",
    size: -1,
    is_array: true,
    element_type: "int2",
  },
  int4: {
    oid: 23,
    name: "int4",
    size: 4,
    is_array: false,
  },
  regproc: {
    oid: 24,
    name: "regproc",
    size: 4,
    is_array: false,
  },
  text: {
    oid: 25,
    name: "text",
    size: -1,
    is_array: false,
  },
  oid: {
    oid: 26,
    name: "oid",
    size: 4,
    is_array: false,
  },
  tid: {
    oid: 27,
    name: "tid",
    size: 6,
    is_array: false,
  },
  xid: {
    oid: 28,
    name: "xid",
    size: 4,
    is_array: false,
  },
  cid: {
    oid: 29,
    name: "cid",
    size: 4,
    is_array: false,
  },
  oidvector: {
    oid: 30,
    name: "oidvector",
    size: -1,
    is_array: true,
    element_type: "oid",
  },
  pg_ddl_command: {
    oid: 32,
    name: "pg_ddl_command",
    size: 8,
    is_array: false,
  },
  pg_type: {
    oid: 71,
    name: "pg_type",
    size: -1,
    is_array: false,
  },
  pg_attribute: {
    oid: 75,
    name: "pg_attribute",
    size: -1,
    is_array: false,
  },
  pg_proc: {
    oid: 81,
    name: "pg_proc",
    size: -1,
    is_array: false,
  },
  pg_class: {
    oid: 83,
    name: "pg_class",
    size: -1,
    is_array: false,
  },
  json: {
    oid: 114,
    name: "json",
    size: -1,
    is_array: false,
  },
  xml: {
    oid: 142,
    name: "xml",
    size: -1,
    is_array: false,
  },
  _xml: {
    oid: 143,
    name: "_xml",
    size: -1,
    is_array: true,
    element_type: "xml",
  },
  pg_node_tree: {
    oid: 194,
    name: "pg_node_tree",
    size: -1,
    is_array: false,
  },
  _json: {
    oid: 199,
    name: "_json",
    size: -1,
    is_array: true,
    element_type: "json",
  },
  smgr: {
    oid: 210,
    name: "smgr",
    size: 2,
    is_array: false,
  },
  point: {
    oid: 600,
    name: "point",
    size: 16,
    is_array: true,
    element_type: "float8",
  },
  lseg: {
    oid: 601,
    name: "lseg",
    size: 32,
    is_array: true,
    element_type: "point",
  },
  path: {
    oid: 602,
    name: "path",
    size: -1,
    is_array: false,
  },
  box: {
    oid: 603,
    name: "box",
    size: 32,
    is_array: true,
    element_type: "point",
  },
  polygon: {
    oid: 604,
    name: "polygon",
    size: -1,
    is_array: false,
  },
  line: {
    oid: 628,
    name: "line",
    size: 24,
    is_array: true,
    element_type: "float8",
  },
  _line: {
    oid: 629,
    name: "_line",
    size: -1,
    is_array: true,
    element_type: "line",
  },
  cidr: {
    oid: 650,
    name: "cidr",
    size: -1,
    is_array: false,
  },
  _cidr: {
    oid: 651,
    name: "_cidr",
    size: -1,
    is_array: true,
    element_type: "cidr",
  },
  float4: {
    oid: 700,
    name: "float4",
    size: 4,
    is_array: false,
  },
  float8: {
    oid: 701,
    name: "float8",
    size: 8,
    is_array: false,
  },
  abstime: {
    oid: 702,
    name: "abstime",
    size: 4,
    is_array: false,
  },
  reltime: {
    oid: 703,
    name: "reltime",
    size: 4,
    is_array: false,
  },
  tinterval: {
    oid: 704,
    name: "tinterval",
    size: 12,
    is_array: false,
  },
  unknown: {
    oid: 705,
    name: "unknown",
    size: -2,
    is_array: false,
  },
  circle: {
    oid: 718,
    name: "circle",
    size: 24,
    is_array: false,
  },
  _circle: {
    oid: 719,
    name: "_circle",
    size: -1,
    is_array: true,
    element_type: "circle",
  },
  money: {
    oid: 790,
    name: "money",
    size: 8,
    is_array: false,
  },
  _money: {
    oid: 791,
    name: "_money",
    size: -1,
    is_array: true,
    element_type: "money",
  },
  macaddr: {
    oid: 829,
    name: "macaddr",
    size: 6,
    is_array: false,
  },
  inet: {
    oid: 869,
    name: "inet",
    size: -1,
    is_array: false,
  },
  _bool: {
    oid: 1000,
    name: "_bool",
    size: -1,
    is_array: true,
    element_type: "bool",
  },
  _bytea: {
    oid: 1001,
    name: "_bytea",
    size: -1,
    is_array: true,
    element_type: "bytea",
  },
  _char: {
    oid: 1002,
    name: "_char",
    size: -1,
    is_array: true,
    element_type: "char",
  },
  _name: {
    oid: 1003,
    name: "_name",
    size: -1,
    is_array: true,
    element_type: "name",
  },
  _int2: {
    oid: 1005,
    name: "_int2",
    size: -1,
    is_array: true,
    element_type: "int2",
  },
  _int2vector: {
    oid: 1006,
    name: "_int2vector",
    size: -1,
    is_array: true,
    element_type: "int2vector",
  },
  _int4: {
    oid: 1007,
    name: "_int4",
    size: -1,
    is_array: true,
    element_type: "int4",
  },
  _regproc: {
    oid: 1008,
    name: "_regproc",
    size: -1,
    is_array: true,
    element_type: "regproc",
  },
  _text: {
    oid: 1009,
    name: "_text",
    size: -1,
    is_array: true,
    element_type: "text",
  },
  _tid: {
    oid: 1010,
    name: "_tid",
    size: -1,
    is_array: true,
    element_type: "tid",
  },
  _xid: {
    oid: 1011,
    name: "_xid",
    size: -1,
    is_array: true,
    element_type: "xid",
  },
  _cid: {
    oid: 1012,
    name: "_cid",
    size: -1,
    is_array: true,
    element_type: "cid",
  },
  _oidvector: {
    oid: 1013,
    name: "_oidvector",
    size: -1,
    is_array: true,
    element_type: "oidvector",
  },
  _bpchar: {
    oid: 1014,
    name: "_bpchar",
    size: -1,
    is_array: true,
    element_type: "bpchar",
  },
  _varchar: {
    oid: 1015,
    name: "_varchar",
    size: -1,
    is_array: true,
    element_type: "varchar",
  },
  _int8: {
    oid: 1016,
    name: "_int8",
    size: -1,
    is_array: true,
    element_type: "int8",
  },
  _point: {
    oid: 1017,
    name: "_point",
    size: -1,
    is_array: true,
    element_type: "point",
  },
  _lseg: {
    oid: 1018,
    name: "_lseg",
    size: -1,
    is_array: true,
    element_type: "lseg",
  },
  _path: {
    oid: 1019,
    name: "_path",
    size: -1,
    is_array: true,
    element_type: "path",
  },
  _box: {
    oid: 1020,
    name: "_box",
    size: -1,
    is_array: true,
    element_type: "box",
  },
  _float4: {
    oid: 1021,
    name: "_float4",
    size: -1,
    is_array: true,
    element_type: "float4",
  },
  _float8: {
    oid: 1022,
    name: "_float8",
    size: -1,
    is_array: true,
    element_type: "float8",
  },
  _abstime: {
    oid: 1023,
    name: "_abstime",
    size: -1,
    is_array: true,
    element_type: "abstime",
  },
  _reltime: {
    oid: 1024,
    name: "_reltime",
    size: -1,
    is_array: true,
    element_type: "reltime",
  },
  _tinterval: {
    oid: 1025,
    name: "_tinterval",
    size: -1,
    is_array: true,
    element_type: "tinterval",
  },
  _polygon: {
    oid: 1027,
    name: "_polygon",
    size: -1,
    is_array: true,
    element_type: "polygon",
  },
  _oid: {
    oid: 1028,
    name: "_oid",
    size: -1,
    is_array: true,
    element_type: "oid",
  },
  aclitem: {
    oid: 1033,
    name: "aclitem",
    size: 12,
    is_array: false,
  },
  _aclitem: {
    oid: 1034,
    name: "_aclitem",
    size: -1,
    is_array: true,
    element_type: "aclitem",
  },
  _macaddr: {
    oid: 1040,
    name: "_macaddr",
    size: -1,
    is_array: true,
    element_type: "macaddr",
  },
  _inet: {
    oid: 1041,
    name: "_inet",
    size: -1,
    is_array: true,
    element_type: "inet",
  },
  bpchar: {
    oid: 1042,
    name: "bpchar",
    size: -1,
    is_array: false,
  },
  varchar: {
    oid: 1043,
    name: "varchar",
    size: -1,
    is_array: false,
  },
  date: {
    oid: 1082,
    name: "date",
    size: 4,
    is_array: false,
  },
  time: {
    oid: 1083,
    name: "time",
    size: 8,
    is_array: false,
  },
  timestamp: {
    oid: 1114,
    name: "timestamp",
    size: 8,
    is_array: false,
  },
  _timestamp: {
    oid: 1115,
    name: "_timestamp",
    size: -1,
    is_array: true,
    element_type: "timestamp",
  },
  _date: {
    oid: 1182,
    name: "_date",
    size: -1,
    is_array: true,
    element_type: "date",
  },
  _time: {
    oid: 1183,
    name: "_time",
    size: -1,
    is_array: true,
    element_type: "time",
  },
  timestamptz: {
    oid: 1184,
    name: "timestamptz",
    size: 8,
    is_array: false,
  },
  _timestamptz: {
    oid: 1185,
    name: "_timestamptz",
    size: -1,
    is_array: true,
    element_type: "timestamptz",
  },
  interval: {
    oid: 1186,
    name: "interval",
    size: 16,
    is_array: false,
  },
  _interval: {
    oid: 1187,
    name: "_interval",
    size: -1,
    is_array: true,
    element_type: "interval",
  },
  _numeric: {
    oid: 1231,
    name: "_numeric",
    size: -1,
    is_array: true,
    element_type: "numeric",
  },
  pg_database: {
    oid: 1248,
    name: "pg_database",
    size: -1,
    is_array: false,
  },
  _cstring: {
    oid: 1263,
    name: "_cstring",
    size: -1,
    is_array: true,
    element_type: "cstring",
  },
  timetz: {
    oid: 1266,
    name: "timetz",
    size: 12,
    is_array: false,
  },
  _timetz: {
    oid: 1270,
    name: "_timetz",
    size: -1,
    is_array: true,
    element_type: "timetz",
  },
  bit: {
    oid: 1560,
    name: "bit",
    size: -1,
    is_array: false,
  },
  _bit: {
    oid: 1561,
    name: "_bit",
    size: -1,
    is_array: true,
    element_type: "bit",
  },
  varbit: {
    oid: 1562,
    name: "varbit",
    size: -1,
    is_array: false,
  },
  _varbit: {
    oid: 1563,
    name: "_varbit",
    size: -1,
    is_array: true,
    element_type: "varbit",
  },
  numeric: {
    oid: 1700,
    name: "numeric",
    size: -1,
    is_array: false,
  },
  refcursor: {
    oid: 1790,
    name: "refcursor",
    size: -1,
    is_array: false,
  },
  _refcursor: {
    oid: 2201,
    name: "_refcursor",
    size: -1,
    is_array: true,
    element_type: "refcursor",
  },
  regprocedure: {
    oid: 2202,
    name: "regprocedure",
    size: 4,
    is_array: false,
  },
  regoper: {
    oid: 2203,
    name: "regoper",
    size: 4,
    is_array: false,
  },
  regoperator: {
    oid: 2204,
    name: "regoperator",
    size: 4,
    is_array: false,
  },
  regclass: {
    oid: 2205,
    name: "regclass",
    size: 4,
    is_array: false,
  },
  regtype: {
    oid: 2206,
    name: "regtype",
    size: 4,
    is_array: false,
  },
  _regprocedure: {
    oid: 2207,
    name: "_regprocedure",
    size: -1,
    is_array: true,
    element_type: "regprocedure",
  },
  _regoper: {
    oid: 2208,
    name: "_regoper",
    size: -1,
    is_array: true,
    element_type: "regoper",
  },
  _regoperator: {
    oid: 2209,
    name: "_regoperator",
    size: -1,
    is_array: true,
    element_type: "regoperator",
  },
  _regclass: {
    oid: 2210,
    name: "_regclass",
    size: -1,
    is_array: true,
    element_type: "regclass",
  },
  _regtype: {
    oid: 2211,
    name: "_regtype",
    size: -1,
    is_array: true,
    element_type: "regtype",
  },
  record: {
    oid: 2249,
    name: "record",
    size: -1,
    is_array: false,
  },
  cstring: {
    oid: 2275,
    name: "cstring",
    size: -2,
    is_array: false,
  },
  any: {
    oid: 2276,
    name: "any",
    size: 4,
    is_array: false,
  },
  anyarray: {
    oid: 2277,
    name: "anyarray",
    size: -1,
    is_array: false,
  },
  void: {
    oid: 2278,
    name: "void",
    size: 4,
    is_array: false,
  },
  trigger: {
    oid: 2279,
    name: "trigger",
    size: 4,
    is_array: false,
  },
  language_handler: {
    oid: 2280,
    name: "language_handler",
    size: 4,
    is_array: false,
  },
  internal: {
    oid: 2281,
    name: "internal",
    size: 8,
    is_array: false,
  },
  opaque: {
    oid: 2282,
    name: "opaque",
    size: 4,
    is_array: false,
  },
  anyelement: {
    oid: 2283,
    name: "anyelement",
    size: 4,
    is_array: false,
  },
  _record: {
    oid: 2287,
    name: "_record",
    size: -1,
    is_array: true,
    element_type: "record",
  },
  anynonarray: {
    oid: 2776,
    name: "anynonarray",
    size: 4,
    is_array: false,
  },
  pg_authid: {
    oid: 2842,
    name: "pg_authid",
    size: -1,
    is_array: false,
  },
  pg_auth_members: {
    oid: 2843,
    name: "pg_auth_members",
    size: -1,
    is_array: false,
  },
  _txid_snapshot: {
    oid: 2949,
    name: "_txid_snapshot",
    size: -1,
    is_array: true,
    element_type: "txid_snapshot",
  },
  uuid: {
    oid: 2950,
    name: "uuid",
    size: 16,
    is_array: false,
  },
  _uuid: {
    oid: 2951,
    name: "_uuid",
    size: -1,
    is_array: true,
    element_type: "uuid",
  },
  txid_snapshot: {
    oid: 2970,
    name: "txid_snapshot",
    size: -1,
    is_array: false,
  },
  fdw_handler: {
    oid: 3115,
    name: "fdw_handler",
    size: 4,
    is_array: false,
  },
  pg_lsn: {
    oid: 3220,
    name: "pg_lsn",
    size: 8,
    is_array: false,
  },
  _pg_lsn: {
    oid: 3221,
    name: "_pg_lsn",
    size: -1,
    is_array: true,
    element_type: "pg_lsn",
  },
  tsm_handler: {
    oid: 3310,
    name: "tsm_handler",
    size: 4,
    is_array: false,
  },
  anyenum: {
    oid: 3500,
    name: "anyenum",
    size: 4,
    is_array: false,
  },
  tsvector: {
    oid: 3614,
    name: "tsvector",
    size: -1,
    is_array: false,
  },
  tsquery: {
    oid: 3615,
    name: "tsquery",
    size: -1,
    is_array: false,
  },
  gtsvector: {
    oid: 3642,
    name: "gtsvector",
    size: -1,
    is_array: false,
  },
  _tsvector: {
    oid: 3643,
    name: "_tsvector",
    size: -1,
    is_array: true,
    element_type: "tsvector",
  },
  _gtsvector: {
    oid: 3644,
    name: "_gtsvector",
    size: -1,
    is_array: true,
    element_type: "gtsvector",
  },
  _tsquery: {
    oid: 3645,
    name: "_tsquery",
    size: -1,
    is_array: true,
    element_type: "tsquery",
  },
  regconfig: {
    oid: 3734,
    name: "regconfig",
    size: 4,
    is_array: false,
  },
  _regconfig: {
    oid: 3735,
    name: "_regconfig",
    size: -1,
    is_array: true,
    element_type: "regconfig",
  },
  regdictionary: {
    oid: 3769,
    name: "regdictionary",
    size: 4,
    is_array: false,
  },
  _regdictionary: {
    oid: 3770,
    name: "_regdictionary",
    size: -1,
    is_array: true,
    element_type: "regdictionary",
  },
  jsonb: {
    oid: 3802,
    name: "jsonb",
    size: -1,
    is_array: false,
  },
  _jsonb: {
    oid: 3807,
    name: "_jsonb",
    size: -1,
    is_array: true,
    element_type: "jsonb",
  },
  anyrange: {
    oid: 3831,
    name: "anyrange",
    size: -1,
    is_array: false,
  },
  event_trigger: {
    oid: 3838,
    name: "event_trigger",
    size: 4,
    is_array: false,
  },
  int4range: {
    oid: 3904,
    name: "int4range",
    size: -1,
    is_array: false,
  },
  _int4range: {
    oid: 3905,
    name: "_int4range",
    size: -1,
    is_array: true,
    element_type: "int4range",
  },
  numrange: {
    oid: 3906,
    name: "numrange",
    size: -1,
    is_array: false,
  },
  _numrange: {
    oid: 3907,
    name: "_numrange",
    size: -1,
    is_array: true,
    element_type: "numrange",
  },
  tsrange: {
    oid: 3908,
    name: "tsrange",
    size: -1,
    is_array: false,
  },
  _tsrange: {
    oid: 3909,
    name: "_tsrange",
    size: -1,
    is_array: true,
    element_type: "tsrange",
  },
  tstzrange: {
    oid: 3910,
    name: "tstzrange",
    size: -1,
    is_array: false,
  },
  _tstzrange: {
    oid: 3911,
    name: "_tstzrange",
    size: -1,
    is_array: true,
    element_type: "tstzrange",
  },
  daterange: {
    oid: 3912,
    name: "daterange",
    size: -1,
    is_array: false,
  },
  _daterange: {
    oid: 3913,
    name: "_daterange",
    size: -1,
    is_array: true,
    element_type: "daterange",
  },
  int8range: {
    oid: 3926,
    name: "int8range",
    size: -1,
    is_array: false,
  },
  _int8range: {
    oid: 3927,
    name: "_int8range",
    size: -1,
    is_array: true,
    element_type: "int8range",
  },
  regnamespace: {
    oid: 4089,
    name: "regnamespace",
    size: 4,
    is_array: false,
  },
  _regnamespace: {
    oid: 4090,
    name: "_regnamespace",
    size: -1,
    is_array: true,
    element_type: "regnamespace",
  },
  regrole: {
    oid: 4096,
    name: "regrole",
    size: 4,
    is_array: false,
  },
  _regrole: {
    oid: 4097,
    name: "_regrole",
    size: -1,
    is_array: true,
    element_type: "regrole",
  },
  pg_attrdef: {
    oid: 10000,
    name: "pg_attrdef",
    size: -1,
    is_array: false,
  },
  pg_constraint: {
    oid: 10001,
    name: "pg_constraint",
    size: -1,
    is_array: false,
  },
  pg_inherits: {
    oid: 10002,
    name: "pg_inherits",
    size: -1,
    is_array: false,
  },
  pg_index: {
    oid: 10003,
    name: "pg_index",
    size: -1,
    is_array: false,
  },
  pg_operator: {
    oid: 10004,
    name: "pg_operator",
    size: -1,
    is_array: false,
  },
  pg_opfamily: {
    oid: 10005,
    name: "pg_opfamily",
    size: -1,
    is_array: false,
  },
  pg_opclass: {
    oid: 10006,
    name: "pg_opclass",
    size: -1,
    is_array: false,
  },
  pg_am: {
    oid: 10155,
    name: "pg_am",
    size: -1,
    is_array: false,
  },
  pg_amop: {
    oid: 10156,
    name: "pg_amop",
    size: -1,
    is_array: false,
  },
  pg_amproc: {
    oid: 10833,
    name: "pg_amproc",
    size: -1,
    is_array: false,
  },
  pg_language: {
    oid: 11370,
    name: "pg_language",
    size: -1,
    is_array: false,
  },
  pg_largeobject_metadata: {
    oid: 11371,
    name: "pg_largeobject_metadata",
    size: -1,
    is_array: false,
  },
  pg_largeobject: {
    oid: 11372,
    name: "pg_largeobject",
    size: -1,
    is_array: false,
  },
  pg_aggregate: {
    oid: 11373,
    name: "pg_aggregate",
    size: -1,
    is_array: false,
  },
  pg_statistic: {
    oid: 11374,
    name: "pg_statistic",
    size: -1,
    is_array: false,
  },
  pg_rewrite: {
    oid: 11375,
    name: "pg_rewrite",
    size: -1,
    is_array: false,
  },
  pg_trigger: {
    oid: 11376,
    name: "pg_trigger",
    size: -1,
    is_array: false,
  },
  pg_event_trigger: {
    oid: 11377,
    name: "pg_event_trigger",
    size: -1,
    is_array: false,
  },
  pg_description: {
    oid: 11378,
    name: "pg_description",
    size: -1,
    is_array: false,
  },
  pg_cast: {
    oid: 11379,
    name: "pg_cast",
    size: -1,
    is_array: false,
  },
  pg_enum: {
    oid: 11593,
    name: "pg_enum",
    size: -1,
    is_array: false,
  },
  pg_namespace: {
    oid: 11594,
    name: "pg_namespace",
    size: -1,
    is_array: false,
  },
  pg_conversion: {
    oid: 11595,
    name: "pg_conversion",
    size: -1,
    is_array: false,
  },
  pg_depend: {
    oid: 11596,
    name: "pg_depend",
    size: -1,
    is_array: false,
  },
  pg_db_role_setting: {
    oid: 11597,
    name: "pg_db_role_setting",
    size: -1,
    is_array: false,
  },
  pg_tablespace: {
    oid: 11598,
    name: "pg_tablespace",
    size: -1,
    is_array: false,
  },
  pg_pltemplate: {
    oid: 11599,
    name: "pg_pltemplate",
    size: -1,
    is_array: false,
  },
  pg_shdepend: {
    oid: 11600,
    name: "pg_shdepend",
    size: -1,
    is_array: false,
  },
  pg_shdescription: {
    oid: 11601,
    name: "pg_shdescription",
    size: -1,
    is_array: false,
  },
  pg_ts_config: {
    oid: 11602,
    name: "pg_ts_config",
    size: -1,
    is_array: false,
  },
  pg_ts_config_map: {
    oid: 11603,
    name: "pg_ts_config_map",
    size: -1,
    is_array: false,
  },
  pg_ts_dict: {
    oid: 11604,
    name: "pg_ts_dict",
    size: -1,
    is_array: false,
  },
  pg_ts_parser: {
    oid: 11605,
    name: "pg_ts_parser",
    size: -1,
    is_array: false,
  },
  pg_ts_template: {
    oid: 11606,
    name: "pg_ts_template",
    size: -1,
    is_array: false,
  },
  pg_extension: {
    oid: 11607,
    name: "pg_extension",
    size: -1,
    is_array: false,
  },
  pg_foreign_data_wrapper: {
    oid: 11608,
    name: "pg_foreign_data_wrapper",
    size: -1,
    is_array: false,
  },
  pg_foreign_server: {
    oid: 11609,
    name: "pg_foreign_server",
    size: -1,
    is_array: false,
  },
  pg_user_mapping: {
    oid: 11610,
    name: "pg_user_mapping",
    size: -1,
    is_array: false,
  },
  pg_foreign_table: {
    oid: 11611,
    name: "pg_foreign_table",
    size: -1,
    is_array: false,
  },
  pg_policy: {
    oid: 11612,
    name: "pg_policy",
    size: -1,
    is_array: false,
  },
  pg_replication_origin: {
    oid: 11613,
    name: "pg_replication_origin",
    size: -1,
    is_array: false,
  },
  pg_default_acl: {
    oid: 11614,
    name: "pg_default_acl",
    size: -1,
    is_array: false,
  },
  pg_seclabel: {
    oid: 11615,
    name: "pg_seclabel",
    size: -1,
    is_array: false,
  },
  pg_shseclabel: {
    oid: 11616,
    name: "pg_shseclabel",
    size: -1,
    is_array: false,
  },
  pg_collation: {
    oid: 11617,
    name: "pg_collation",
    size: -1,
    is_array: false,
  },
  pg_range: {
    oid: 11618,
    name: "pg_range",
    size: -1,
    is_array: false,
  },
  pg_transform: {
    oid: 11619,
    name: "pg_transform",
    size: -1,
    is_array: false,
  },
  pg_toast_2604: {
    oid: 11620,
    name: "pg_toast_2604",
    size: -1,
    is_array: false,
  },
  pg_toast_2606: {
    oid: 11621,
    name: "pg_toast_2606",
    size: -1,
    is_array: false,
  },
  pg_toast_2609: {
    oid: 11622,
    name: "pg_toast_2609",
    size: -1,
    is_array: false,
  },
  pg_toast_1255: {
    oid: 11623,
    name: "pg_toast_1255",
    size: -1,
    is_array: false,
  },
  pg_toast_2618: {
    oid: 11624,
    name: "pg_toast_2618",
    size: -1,
    is_array: false,
  },
  pg_toast_3596: {
    oid: 11625,
    name: "pg_toast_3596",
    size: -1,
    is_array: false,
  },
  pg_toast_2619: {
    oid: 11626,
    name: "pg_toast_2619",
    size: -1,
    is_array: false,
  },
  pg_toast_2620: {
    oid: 11627,
    name: "pg_toast_2620",
    size: -1,
    is_array: false,
  },
  pg_toast_2396: {
    oid: 11628,
    name: "pg_toast_2396",
    size: -1,
    is_array: false,
  },
  pg_toast_2964: {
    oid: 11629,
    name: "pg_toast_2964",
    size: -1,
    is_array: false,
  },
  pg_toast_3592: {
    oid: 11630,
    name: "pg_toast_3592",
    size: -1,
    is_array: false,
  },
  pg_roles: {
    oid: 11632,
    name: "pg_roles",
    size: -1,
    is_array: false,
  },
  pg_shadow: {
    oid: 11636,
    name: "pg_shadow",
    size: -1,
    is_array: false,
  },
  pg_group: {
    oid: 11640,
    name: "pg_group",
    size: -1,
    is_array: false,
  },
  pg_user: {
    oid: 11643,
    name: "pg_user",
    size: -1,
    is_array: false,
  },
  pg_policies: {
    oid: 11646,
    name: "pg_policies",
    size: -1,
    is_array: false,
  },
  pg_rules: {
    oid: 11650,
    name: "pg_rules",
    size: -1,
    is_array: false,
  },
  pg_views: {
    oid: 11654,
    name: "pg_views",
    size: -1,
    is_array: false,
  },
  pg_tables: {
    oid: 11658,
    name: "pg_tables",
    size: -1,
    is_array: false,
  },
  pg_matviews: {
    oid: 11662,
    name: "pg_matviews",
    size: -1,
    is_array: false,
  },
  pg_indexes: {
    oid: 11666,
    name: "pg_indexes",
    size: -1,
    is_array: false,
  },
  pg_stats: {
    oid: 11670,
    name: "pg_stats",
    size: -1,
    is_array: false,
  },
  pg_locks: {
    oid: 11674,
    name: "pg_locks",
    size: -1,
    is_array: false,
  },
  pg_cursors: {
    oid: 11677,
    name: "pg_cursors",
    size: -1,
    is_array: false,
  },
  pg_available_extensions: {
    oid: 11680,
    name: "pg_available_extensions",
    size: -1,
    is_array: false,
  },
  pg_available_extension_versions: {
    oid: 11683,
    name: "pg_available_extension_versions",
    size: -1,
    is_array: false,
  },
  pg_prepared_xacts: {
    oid: 11686,
    name: "pg_prepared_xacts",
    size: -1,
    is_array: false,
  },
  pg_prepared_statements: {
    oid: 11690,
    name: "pg_prepared_statements",
    size: -1,
    is_array: false,
  },
  pg_seclabels: {
    oid: 11693,
    name: "pg_seclabels",
    size: -1,
    is_array: false,
  },
  pg_settings: {
    oid: 11697,
    name: "pg_settings",
    size: -1,
    is_array: false,
  },
  pg_file_settings: {
    oid: 11702,
    name: "pg_file_settings",
    size: -1,
    is_array: false,
  },
  pg_timezone_abbrevs: {
    oid: 11705,
    name: "pg_timezone_abbrevs",
    size: -1,
    is_array: false,
  },
  pg_timezone_names: {
    oid: 11708,
    name: "pg_timezone_names",
    size: -1,
    is_array: false,
  },
  pg_stat_all_tables: {
    oid: 11711,
    name: "pg_stat_all_tables",
    size: -1,
    is_array: false,
  },
  pg_stat_xact_all_tables: {
    oid: 11715,
    name: "pg_stat_xact_all_tables",
    size: -1,
    is_array: false,
  },
  pg_stat_sys_tables: {
    oid: 11719,
    name: "pg_stat_sys_tables",
    size: -1,
    is_array: false,
  },
  pg_stat_xact_sys_tables: {
    oid: 11723,
    name: "pg_stat_xact_sys_tables",
    size: -1,
    is_array: false,
  },
  pg_stat_user_tables: {
    oid: 11726,
    name: "pg_stat_user_tables",
    size: -1,
    is_array: false,
  },
  pg_stat_xact_user_tables: {
    oid: 11730,
    name: "pg_stat_xact_user_tables",
    size: -1,
    is_array: false,
  },
  pg_statio_all_tables: {
    oid: 11733,
    name: "pg_statio_all_tables",
    size: -1,
    is_array: false,
  },
  pg_statio_sys_tables: {
    oid: 11737,
    name: "pg_statio_sys_tables",
    size: -1,
    is_array: false,
  },
  pg_statio_user_tables: {
    oid: 11740,
    name: "pg_statio_user_tables",
    size: -1,
    is_array: false,
  },
  pg_stat_all_indexes: {
    oid: 11743,
    name: "pg_stat_all_indexes",
    size: -1,
    is_array: false,
  },
  pg_stat_sys_indexes: {
    oid: 11747,
    name: "pg_stat_sys_indexes",
    size: -1,
    is_array: false,
  },
  pg_stat_user_indexes: {
    oid: 11750,
    name: "pg_stat_user_indexes",
    size: -1,
    is_array: false,
  },
  pg_statio_all_indexes: {
    oid: 11753,
    name: "pg_statio_all_indexes",
    size: -1,
    is_array: false,
  },
  pg_statio_sys_indexes: {
    oid: 11757,
    name: "pg_statio_sys_indexes",
    size: -1,
    is_array: false,
  },
  pg_statio_user_indexes: {
    oid: 11760,
    name: "pg_statio_user_indexes",
    size: -1,
    is_array: false,
  },
  pg_statio_all_sequences: {
    oid: 11763,
    name: "pg_statio_all_sequences",
    size: -1,
    is_array: false,
  },
  pg_statio_sys_sequences: {
    oid: 11767,
    name: "pg_statio_sys_sequences",
    size: -1,
    is_array: false,
  },
  pg_statio_user_sequences: {
    oid: 11770,
    name: "pg_statio_user_sequences",
    size: -1,
    is_array: false,
  },
  pg_stat_activity: {
    oid: 11773,
    name: "pg_stat_activity",
    size: -1,
    is_array: false,
  },
  pg_stat_replication: {
    oid: 11777,
    name: "pg_stat_replication",
    size: -1,
    is_array: false,
  },
  pg_stat_ssl: {
    oid: 11781,
    name: "pg_stat_ssl",
    size: -1,
    is_array: false,
  },
  pg_replication_slots: {
    oid: 11784,
    name: "pg_replication_slots",
    size: -1,
    is_array: false,
  },
  pg_stat_database: {
    oid: 11788,
    name: "pg_stat_database",
    size: -1,
    is_array: false,
  },
  pg_stat_database_conflicts: {
    oid: 11791,
    name: "pg_stat_database_conflicts",
    size: -1,
    is_array: false,
  },
  pg_stat_user_functions: {
    oid: 11794,
    name: "pg_stat_user_functions",
    size: -1,
    is_array: false,
  },
  pg_stat_xact_user_functions: {
    oid: 11798,
    name: "pg_stat_xact_user_functions",
    size: -1,
    is_array: false,
  },
  pg_stat_archiver: {
    oid: 11802,
    name: "pg_stat_archiver",
    size: -1,
    is_array: false,
  },
  pg_stat_bgwriter: {
    oid: 11805,
    name: "pg_stat_bgwriter",
    size: -1,
    is_array: false,
  },
  pg_user_mappings: {
    oid: 11808,
    name: "pg_user_mappings",
    size: -1,
    is_array: false,
  },
  pg_replication_origin_status: {
    oid: 11812,
    name: "pg_replication_origin_status",
    size: -1,
    is_array: false,
  },
  cardinal_number: {
    oid: 13015,
    name: "cardinal_number",
    size: 4,
    is_array: false,
  },
  character_data: {
    oid: 13017,
    name: "character_data",
    size: -1,
    is_array: false,
  },
  sql_identifier: {
    oid: 13018,
    name: "sql_identifier",
    size: -1,
    is_array: false,
  },
  information_schema_catalog_name: {
    oid: 13020,
    name: "information_schema_catalog_name",
    size: -1,
    is_array: false,
  },
  time_stamp: {
    oid: 13022,
    name: "time_stamp",
    size: 8,
    is_array: false,
  },
  yes_or_no: {
    oid: 13023,
    name: "yes_or_no",
    size: -1,
    is_array: false,
  },
  applicable_roles: {
    oid: 13026,
    name: "applicable_roles",
    size: -1,
    is_array: false,
  },
  administrable_role_authorizations: {
    oid: 13030,
    name: "administrable_role_authorizations",
    size: -1,
    is_array: false,
  },
  attributes: {
    oid: 13033,
    name: "attributes",
    size: -1,
    is_array: false,
  },
  character_sets: {
    oid: 13037,
    name: "character_sets",
    size: -1,
    is_array: false,
  },
  check_constraint_routine_usage: {
    oid: 13041,
    name: "check_constraint_routine_usage",
    size: -1,
    is_array: false,
  },
  check_constraints: {
    oid: 13045,
    name: "check_constraints",
    size: -1,
    is_array: false,
  },
  collations: {
    oid: 13049,
    name: "collations",
    size: -1,
    is_array: false,
  },
  collation_character_set_applicability: {
    oid: 13052,
    name: "collation_character_set_applicability",
    size: -1,
    is_array: false,
  },
  column_domain_usage: {
    oid: 13055,
    name: "column_domain_usage",
    size: -1,
    is_array: false,
  },
  column_privileges: {
    oid: 13059,
    name: "column_privileges",
    size: -1,
    is_array: false,
  },
  column_udt_usage: {
    oid: 13063,
    name: "column_udt_usage",
    size: -1,
    is_array: false,
  },
  columns: {
    oid: 13067,
    name: "columns",
    size: -1,
    is_array: false,
  },
  constraint_column_usage: {
    oid: 13071,
    name: "constraint_column_usage",
    size: -1,
    is_array: false,
  },
  constraint_table_usage: {
    oid: 13075,
    name: "constraint_table_usage",
    size: -1,
    is_array: false,
  },
  domain_constraints: {
    oid: 13079,
    name: "domain_constraints",
    size: -1,
    is_array: false,
  },
  domain_udt_usage: {
    oid: 13083,
    name: "domain_udt_usage",
    size: -1,
    is_array: false,
  },
  domains: {
    oid: 13086,
    name: "domains",
    size: -1,
    is_array: false,
  },
  enabled_roles: {
    oid: 13090,
    name: "enabled_roles",
    size: -1,
    is_array: false,
  },
  key_column_usage: {
    oid: 13093,
    name: "key_column_usage",
    size: -1,
    is_array: false,
  },
  parameters: {
    oid: 13097,
    name: "parameters",
    size: -1,
    is_array: false,
  },
  referential_constraints: {
    oid: 13101,
    name: "referential_constraints",
    size: -1,
    is_array: false,
  },
  role_column_grants: {
    oid: 13105,
    name: "role_column_grants",
    size: -1,
    is_array: false,
  },
  routine_privileges: {
    oid: 13108,
    name: "routine_privileges",
    size: -1,
    is_array: false,
  },
  role_routine_grants: {
    oid: 13112,
    name: "role_routine_grants",
    size: -1,
    is_array: false,
  },
  routines: {
    oid: 13115,
    name: "routines",
    size: -1,
    is_array: false,
  },
  schemata: {
    oid: 13119,
    name: "schemata",
    size: -1,
    is_array: false,
  },
  sequences: {
    oid: 13122,
    name: "sequences",
    size: -1,
    is_array: false,
  },
  sql_features: {
    oid: 13126,
    name: "sql_features",
    size: -1,
    is_array: false,
  },
  pg_toast_13125: {
    oid: 13128,
    name: "pg_toast_13125",
    size: -1,
    is_array: false,
  },
  sql_implementation_info: {
    oid: 13131,
    name: "sql_implementation_info",
    size: -1,
    is_array: false,
  },
  pg_toast_13130: {
    oid: 13133,
    name: "pg_toast_13130",
    size: -1,
    is_array: false,
  },
  sql_languages: {
    oid: 13136,
    name: "sql_languages",
    size: -1,
    is_array: false,
  },
  pg_toast_13135: {
    oid: 13138,
    name: "pg_toast_13135",
    size: -1,
    is_array: false,
  },
  sql_packages: {
    oid: 13141,
    name: "sql_packages",
    size: -1,
    is_array: false,
  },
  pg_toast_13140: {
    oid: 13143,
    name: "pg_toast_13140",
    size: -1,
    is_array: false,
  },
  sql_parts: {
    oid: 13146,
    name: "sql_parts",
    size: -1,
    is_array: false,
  },
  pg_toast_13145: {
    oid: 13148,
    name: "pg_toast_13145",
    size: -1,
    is_array: false,
  },
  sql_sizing: {
    oid: 13151,
    name: "sql_sizing",
    size: -1,
    is_array: false,
  },
  pg_toast_13150: {
    oid: 13153,
    name: "pg_toast_13150",
    size: -1,
    is_array: false,
  },
  sql_sizing_profiles: {
    oid: 13156,
    name: "sql_sizing_profiles",
    size: -1,
    is_array: false,
  },
  pg_toast_13155: {
    oid: 13158,
    name: "pg_toast_13155",
    size: -1,
    is_array: false,
  },
  table_constraints: {
    oid: 13161,
    name: "table_constraints",
    size: -1,
    is_array: false,
  },
  table_privileges: {
    oid: 13165,
    name: "table_privileges",
    size: -1,
    is_array: false,
  },
  role_table_grants: {
    oid: 13169,
    name: "role_table_grants",
    size: -1,
    is_array: false,
  },
  tables: {
    oid: 13172,
    name: "tables",
    size: -1,
    is_array: false,
  },
  transforms: {
    oid: 13176,
    name: "transforms",
    size: -1,
    is_array: false,
  },
  triggered_update_columns: {
    oid: 13180,
    name: "triggered_update_columns",
    size: -1,
    is_array: false,
  },
  triggers: {
    oid: 13184,
    name: "triggers",
    size: -1,
    is_array: false,
  },
  udt_privileges: {
    oid: 13188,
    name: "udt_privileges",
    size: -1,
    is_array: false,
  },
  role_udt_grants: {
    oid: 13192,
    name: "role_udt_grants",
    size: -1,
    is_array: false,
  },
  usage_privileges: {
    oid: 13195,
    name: "usage_privileges",
    size: -1,
    is_array: false,
  },
  role_usage_grants: {
    oid: 13199,
    name: "role_usage_grants",
    size: -1,
    is_array: false,
  },
  user_defined_types: {
    oid: 13202,
    name: "user_defined_types",
    size: -1,
    is_array: false,
  },
  view_column_usage: {
    oid: 13206,
    name: "view_column_usage",
    size: -1,
    is_array: false,
  },
  view_routine_usage: {
    oid: 13210,
    name: "view_routine_usage",
    size: -1,
    is_array: false,
  },
  view_table_usage: {
    oid: 13214,
    name: "view_table_usage",
    size: -1,
    is_array: false,
  },
  views: {
    oid: 13218,
    name: "views",
    size: -1,
    is_array: false,
  },
  data_type_privileges: {
    oid: 13222,
    name: "data_type_privileges",
    size: -1,
    is_array: false,
  },
  element_types: {
    oid: 13226,
    name: "element_types",
    size: -1,
    is_array: false,
  },
  _pg_foreign_table_columns: {
    oid: 13230,
    name: "_pg_foreign_table_columns",
    size: -1,
    is_array: false,
  },
  column_options: {
    oid: 13234,
    name: "column_options",
    size: -1,
    is_array: false,
  },
  _pg_foreign_data_wrappers: {
    oid: 13237,
    name: "_pg_foreign_data_wrappers",
    size: -1,
    is_array: false,
  },
  foreign_data_wrapper_options: {
    oid: 13240,
    name: "foreign_data_wrapper_options",
    size: -1,
    is_array: false,
  },
  foreign_data_wrappers: {
    oid: 13243,
    name: "foreign_data_wrappers",
    size: -1,
    is_array: false,
  },
  _pg_foreign_servers: {
    oid: 13246,
    name: "_pg_foreign_servers",
    size: -1,
    is_array: false,
  },
  foreign_server_options: {
    oid: 13250,
    name: "foreign_server_options",
    size: -1,
    is_array: false,
  },
  foreign_servers: {
    oid: 13253,
    name: "foreign_servers",
    size: -1,
    is_array: false,
  },
  _pg_foreign_tables: {
    oid: 13256,
    name: "_pg_foreign_tables",
    size: -1,
    is_array: false,
  },
  foreign_table_options: {
    oid: 13260,
    name: "foreign_table_options",
    size: -1,
    is_array: false,
  },
  foreign_tables: {
    oid: 13263,
    name: "foreign_tables",
    size: -1,
    is_array: false,
  },
  _pg_user_mappings: {
    oid: 13266,
    name: "_pg_user_mappings",
    size: -1,
    is_array: false,
  },
  user_mapping_options: {
    oid: 13270,
    name: "user_mapping_options",
    size: -1,
    is_array: false,
  },
  user_mappings: {
    oid: 13274,
    name: "user_mappings",
    size: -1,
    is_array: false,
  }
};

exports.ERROR_FIELD_ID_MAP = ERROR_FIELD_ID_MAP;
exports.SQLSTATE_ERROR_CODE_MAP = SQLSTATE_ERROR_CODE_MAP;
exports.PG_TYPE_MAP = PG_TYPE_MAP;
